"""Canonical endoscopic anatomy labels used by realtime classification."""

IMAGE_LABELS = [
	"Proximal esophagus",
	"Mid esophagus",
	"Distal esophagus",
	"Z-line",
	"Gastroesophageal junction (GEJ)",
	"Cardia",
	"Fundus",
	"Body",
	"Incisura angularis",
	"Antrum",
	"Pylorus",
	"Duodenal bulb (D1)",
	"Second portion of duodenum (D2)",
	"Third portion (D3)",
	"Fourth portion (D4)",
	"Cecum",
	"Ascending colon",
	"Hepatic flexure",
	"Transverse colon",
	"Splenic flexure",
	"Descending colon",
	"Sigmoid colon",
	"Rectum",
	"Terminal ileum",
	"Anorectal junction",
]
